[env:lilygo-t-display-s3]
platform = espressif32
board = lilygo-t-display-s3
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
lib_deps = 
	tttapa/Control Surface@^2.1.0
	bodmer/TFT_eSPI@^2.5.43
build_flags = 
	-O3
	-ffast-math
	
	-D ARDUINO_USB_MODE=0
	-D CORE_DEBUG_LEVEL=0
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D USB_MANUFACTURER="\"T-Display\""
	-D USB_PRODUCT="\"T-Display\""
	
	-fsingle-precision-constant
	
	-D TOUCH_CS=-1
	-I lib/esp-dsp/modules/fft/include
	-I lib/esp-dsp/modules/common/include
	-I lib/esp-dsp/modules/math/include
	-I lib/esp-dsp/modules/wind/include

	; --- NEW SCREEN CONFIG METHOD ---
	-D USER_SETUP_LOADED=1
	-include tft_setup.h